version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bankerize_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - bankerize
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: bankerize_webserver
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - bankerize
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: bankerize_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankerize
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - bankerize

networks:
  bankerize:
    driver: bridge
